name: Python Safety Check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build setuptools wheel

    - name: Install safety
      run: pip install safety

    - name: Safety Check
      run: safety check -r requirements.txt
